START TRANSACTION;

CREATE TABLE IF NOT EXISTS "DataProtectionKeys" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FriendlyName" text,
    "Xml" text,
    CONSTRAINT "PK_DataProtectionKeys" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Messages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Text" text NOT NULL,
    "Timestamp" timestamp NOT NULL,
    CONSTRAINT "PK_Messages" PRIMARY KEY ("Id")
);

COMMIT;